- examples/pagination/keyset/connector.py
- examples/pagination/next_page_url/connector.py
- examples/pagination/offset_based/connector.py
- examples/pagination/page_number/connector.py
Add missing yield for checkpoint operations in the pagination examples.
> fix(examples): add yield for checkpoint in pagination examples

- README.md
- examples/source_examples/toast/configuration.json
- examples/source_examples/toast/connector.py
- examples/source_examples/toast/requirements.txt
Many customers are going to be asking for this for the [Toast API](https://doc.toasttab.com/openapi/). This is a very simple example and is not a replacement for the existing connector.
> Add Toast example

- .github/workflows/enforce-readme-update.yml
Closes https://fivetran.height.app/T-906794
Added Github Action to prevent merging of PRs if readme is not updated while adding new examples.
Testing:
- [This PR build passes](https://github.com/fivetran/fivetran_connector_sdk/actions/runs/13781394837/job/38540140703?pr=91) as changes are made only to `.github` directory which is excluded
- Existing example update [build passes](https://github.com/fivetran/fivetran_connector_sdk/actions/runs/13781411507/job/38540186001?pr=92) as expected
- New example without readme [build fails](https://github.com/fivetran/fivetran_connector_sdk/actions/runs/13781434550/job/38540250477?pr=93) as expected
- New example with readme [build passes](https://github.com/fivetran/fivetran_connector_sdk/actions/runs/13781518270/job/38540479793?pr=94) as expected
> feature(examples): add github action to check for readme updates

- examples/quickstart_examples/weather/configuration.json
- examples/quickstart_examples/weather/connector.py
Closes https://fivetran.height.app/T-913363
Updated Weather example to make forecast location configurable via configuration.json with default values as fallback.
Without any `configuration.json`
With `configuration.json`
> feature(examples): add way to provide location for weather example and fix comment

- README.md
closes https://fivetran.height.app/T-919133
- The blog link in the main readme was broken.
- correct link added : https://www.fivetran.com/blog/building-a-fivetran-connector-in-1-hour-with-anthropics-claude-ai
> task(readme) : fixed broken blog link in README.md

- examples/common_patterns_for_connectors/cursors/multiple_tables_with_cursors/connector.py
Closes https://fivetran.height.app/T-923692
Fixes PK in department table, where records were getting overwritten due to the same PKs.
###Testing
> fix(example): fix PK for multiple_table_with_cursors example

- README.md
Links https://fivetran.height.app/T-898484
We need these tags to render the markdown in Fivetran docs.
Ref: https://github.com/fivetran/engineering/pull/214552
> fix(readme): update the details tag

- README.md
Links https://fivetran.height.app/T-898484
We need these tags to render the markdown in Fivetran docs.
Ref: https://github.com/fivetran/engineering/pull/214552
> fix(readme): update open tag as per Fivetran docs rendering

- README.md
Update README Private Preview Example link to use full URL. This is required because the page is embedded in docs. Relative URLs cause a 404 in docs.
> Update README Private Preview Example link

- template_example_connector/README_template.md
One heading uses title capitalization instead of sentence capitalization
> README_template: Fix capitalization in a header

- examples/source_examples/toast/configuration.json
This adds fields in configuration.json that were missed during the last PR.
Closes [https://fivetran.height.app/T-977971](https://fivetran.height.app/T-977971)
`configuration.json was missing two fields: key and initialSyncStart. These are mentioned in the README.md but they weren't in the file.`
`This is the configuration file that TopGolf and EatWell are both using.`
> fix(configuration.json): add missing keys to Toast connector

- examples/quickstart_examples/base_64_encoding_decoding/README.md
- examples/quickstart_examples/complex_configuration_options/README.md
- examples/quickstart_examples/configuration/README.md
- examples/quickstart_examples/hello/README.md
- examples/quickstart_examples/large_data_set/with_pagination/README.md
- examples/quickstart_examples/large_data_set/without_pagination/README.md
- examples/quickstart_examples/multiple_code_files/README.md
- examples/quickstart_examples/simple_three_step_cursor/README.md
- examples/quickstart_examples/using_pd_dataframes/README.md
Link https://fivetran.atlassian.net/browse/RD-1008188
Added missing readme.md files for Quickstart examples.
> fix(examples): add missing readme for quickstart examples

- examples/common_patterns_for_connectors/priority_first_sync_for_high_volume_initial_syncs/README.md
- examples/common_patterns_for_connectors/records_with_no_created_at_timestamp/README.md
- examples/common_patterns_for_connectors/schema_from_database/README.md
- examples/common_patterns_for_connectors/specified_types/README.md
- examples/common_patterns_for_connectors/three_operations/README.md
- examples/common_patterns_for_connectors/unspecified_types/README.md
Link https://fivetran.atlassian.net/browse/RD-1008188
Added missing readme.md files for Common Patterns Examples.
> fix(examples): add missing readme for common patterns examples

- README.md
- examples/quickstart_examples/parsing_json_response_in_class/README.md
- examples/quickstart_examples/parsing_json_response_in_class/connector.py
Closes https://fivetran.atlassian.net/browse/RD-982927
Added new example for parsing API response via class, POJO style.
> feature(example): added new example for parsing API response via class

- .github/workflows/code-quality-check.yml
Closes https://fivetran.atlassian.net/browse/RD-968977
We have made Code Quality check required for all the PRs, so to prevent blocking of PRs without any Python files, we need to ensure this action runs even for them.
> fix(workflows): remove python files trigger as the check is required for all PRs

- README.md
Links https://fivetran.atlassian.net/browse/RD-1014559
Mention in the readme about the new release and mention that `AI and Connector SDK` still uses yield, which will be replaced.
> doc(cSDK): Add notes in README about 2.0.0 release

- examples/common_patterns_for_connectors/parallel_fetching_from_source/connector.py
- examples/quickstart_examples/large_data_set/without_pagination/connector.py
Links https://fivetran.atlassian.net/browse/RD-1014559
Improve example as yield is not required in this case
- fivetran debug (replaced the source call with mock data to check the behaviour)
> refactor(cSDK): Improve parallel fetching example

- examples/source_examples/ibm_informix_using_ibm_db/README.md
Closes https://fivetran.atlassian.net/browse/RD-963258
- Adding the troubleshooting for ImportError in windows while running the IBM Informix example
- Not needed
> fix(cSDK): Adding troubleshooting in readme file for informix

- examples/quickstart_examples/base_64_encoding_decoding/connector.py
- examples/quickstart_examples/complex_configuration_options/connector.py
- examples/quickstart_examples/configuration/connector.py
- examples/quickstart_examples/hello/connector.py
- examples/quickstart_examples/large_data_set/with_pagination/connector.py
- examples/quickstart_examples/large_data_set/without_pagination/connector.py
- examples/quickstart_examples/multiple_code_files/connector.py
- examples/quickstart_examples/multiple_code_files/timestamp_serializer.py
- examples/quickstart_examples/oop_example/connector.py
- examples/quickstart_examples/simple_three_step_cursor/connector.py
- examples/quickstart_examples/using_pd_dataframes/connector.py
- examples/quickstart_examples/weather_with_configuration/connector.py
Closes https://fivetran.atlassian.net/browse/RD-1021873
Formatting the Quickstart examples according to the template connector.
The changes done are:
- Added `validate_configuration()` in the connectors using `configuration.json`
- Moved the comments inside the method docstring ( as defined in the template connector )
- Added method docstring in methods ( where missing )
The changes are done only in the Quickstart examples
Minor changes in the comments and docstrings. No logical changes done
> task(cSDK): Formatting the Quickstart Examples according to template

- template_example_connector/README_template.md
Adds instructions for optional ERD addition.
Reproduces https://github.com/fivetran/fivetran_connector_sdk/pull/265 that I closed due to merge conflict
https://fivetran.atlassian.net/browse/RD-1032149
Adds an optional ERD image to template README
> Enhance README template with ERD and file details

- .github/workflows/code-quality-check.yml
Closes https://fivetran.atlassian.net/browse/RD-1034402
Add a step to check if comments can be posted on PRs. If yes, allow putting comments, else skip it.
`continue-on-error` field makes sure that if comment can't be posted it would skip it.
- Created a sample PR from fork: https://github.com/fivetran/fivetran_connector_sdk/pull/278
> Creating or updating comment failed, but it was ignored if it doesn't have permission
> Failed with check failure
> fix(code_quality_check): Ignore writing comment if no permission

- .github/workflows/code-quality-check.yml
Closes `<ADD TICKET LINK HERE, EACH PR MUST BE LINKED TO A JIRA TICKET>`
The code quality check fails with NameError
Fixing by upfront assignment of the run_url which is causing the NameError
`<MENTION ABOUT YOUR TESTING DETAILS HERE, ATTACH SCREENSHOTS IF NEEDED (WITHOUT PII)>`
> task(cSDK): Fix duplicate run_url assignment in workflow
