README.md
Addressing learning from Dan session on 14 Mar 2024.
He wasn't sure on first setup what code structure was needed and tried running the debug command before he create a connector.py file to actually contain a connector.
=> Make required code structure clearer for easier user setup

README.md
Polishing the readme a little based on Dan Belknap's user test - where he didn't include needed configuration when attempting to deploy. This will also provide a barebones docs for how configuration works - more will be needed and will be added in separate PRs.
=> Adding clarification of how to deploy with configuration.

examples/user_profiles/connector.py, examples/user_profiles/requirements.txt
Closes https://fivetran.height.app/T-742626
Added an example for connector SDK which uses pandas Dataframes to process and upsert the data.
- `fivetran debug` output
- `Connector creation` output (Pending)
=> Added an example for Connector SDK

README.md
=> doc(README): Add example in ReadMe

README.md, examples/pagination/keyset/connector.py, examples/pagination/next_page_url/connector.py, examples/pagination/offset_based/connector.py, examples/pagination/page_number/connector.py
Closes https://fivetran.height.app/T-742627
Added examples for the following types of paginations:
- Next Page URL Pagination
- Offset-Based Pagination
- Page Number Pagination
- Keyset Pagination
=> feature(examples): added examples for different types of paginations

README.md
Add missing example link to Readme for better visibility
=> fix(readme): add link to missing example

README.md
- Updating the supported python version in the docs
=> docs(sdk): updated with supported python versions

README.md
Downgrade python version to 3.11 in docs
=> docs(connector-sdk): Downgrade python version to 3.11 in docs

examples/redshift/configuration.json, examples/redshift/connector.py, examples/redshift/requirements.txt
Example to show how we can sync records from redshift DB via Connector SDK
=> feature(connector_sdk): Redshift DB example

README.md
Closes https://fivetran.height.app/T-795872
Added disclaimer about MAR and charging of example connectors.
=> fix(readme): added reminders about MAR and other tips

examples/quick_start_examples/multiple_code_files/connector.py
Remove incorrect comment line.
example uses schema()
add explanation for __init__ file
[T-810815](https://fivetran.height.app/T-810815)
=> Correct Example comment

examples/common_patterns_for_connectors/cursors/marketstack/configuration.json, examples/common_patterns_for_connectors/cursors/marketstack/connector.py, examples/database_source_examples/redshift/configuration.json
Ticket: 805408
Refactoring the example based on the requested changes.
=> refactor(Marketstack): Simplify the example and provide links where required

examples/common_patterns_for_connectors/cursors/marketstack/connector.py, examples/common_patterns_for_connectors/cursors/multiple_tables_with_cursors/connector.py, examples/common_patterns_for_connectors/hashes/connector.py, examples/common_patterns_for_connectors/pagination/keyset/connector.py, examples/common_patterns_for_connectors/pagination/next_page_url/connector.py, examples/common_patterns_for_connectors/pagination/offset_based/connector.py, examples/common_patterns_for_connectors/pagination/page_number/connector.py, examples/common_patterns_for_connectors/priority_first_sync_for_high_volume_initial_syncs/connector.py, examples/common_patterns_for_connectors/records_with_no_created_at_timestamp/connector.py, examples/common_patterns_for_connectors/specified_types/connector.py, examples/common_patterns_for_connectors/three_operations/connector.py, examples/common_patterns_for_connectors/unspecified_types/connector.py, examples/quickstart_examples/configuration/connector.py, examples/quickstart_examples/hello/connector.py, examples/quickstart_examples/multiple_code_files/connector.py, examples/quickstart_examples/simple_three_step_cursor/connector.py, examples/quickstart_examples/user_profiles/connector.py, examples/quickstart_examples/weather/connector.py, examples/source_examples/aws_dynamo_db_authentication/connector.py, examples/source_examples/common_patterns/key_based_replication/connector.py, examples/source_examples/redshift/connector.py
Closes https://fivetran.height.app/T-805250
=> fix(examples): add example logs and fix naming

README.md, examples/quickstart_examples/complex_configuration_options/configuration.json, examples/quickstart_examples/complex_configuration_options/connector.py
Closes https://fivetran.height.app/T-822812
**Testing**
* Tested locally, the config fields are properly casted.
Example showing casting config field to list, integer and boolean in update method.
=> Feature(ConnectorSdk): Config Options Example

README.md
Minor doc changes as per PM's [suggestion](https://github.com/fivetran/fivetran_connector_sdk/pull/57#discussion_r1865931963).
=> Tweak(Docs): Fix usage of verb

README.md, examples/common_patterns_for_connectors/export/csv/connector.py
Closes https://fivetran.height.app/T-834230
Corresponding PyPI package changes: https://github.com/fivetran/engineering/pull/201251
=> feature(example): added export example with CSV response type

examples/quickstart_examples/multiple_code_files/connector.py
Closes https://fivetran.height.app/T-852752
=> Fix(SDK): Remove incorrect line from comments

examples/source_examples/oauth2_and_accelo_api_connector_multithreading_enabled/requirements.txt
Closes https://fivetran.height.app/T-899140
Removes preinstalled requests dependency.
=> Fix(ConnectorSdk): Remove Requests Dependency

examples/quickstart_examples/configuration/requirements.txt, examples/quickstart_examples/using_pd_dataframes/requirements.txt, examples/source_examples/aws_dynamo_db_authentication/requirements.txt
Closes https://fivetran.height.app/T-899140
Testing Details:
- Created connectors for all examples where requirements was changed and ran a sync.
=> feature(connector_sdk): Update requirements whenever necessary

README.md, examples/source_examples/gcp_pub_sub/README.md, examples/source_examples/gcp_pub_sub/configuration.json, examples/source_examples/gcp_pub_sub/connector.py, examples/source_examples/gcp_pub_sub/requirements.txt
Closes https://fivetran.height.app/T-912955
- Added an example to show how to sync the data from GCP pub sub.
=> feature(connector-sdk) : adding gcp pub sub example

examples/common_patterns_for_connectors/cursors/multiple_tables_with_cursors/connector.py
Making the timestamps for the second department unique so the state management is clearer.
=> fix(examples): update state usage example

README.md, examples/source_examples/github_traffic/README.md, examples/source_examples/github_traffic/configuration.json, examples/source_examples/github_traffic/connector.py
Closes https://fivetran.height.app/T-925765
Added example to sync GitHub repo traffic data using Connector SDK.
=> feature(examples): added example for github repo traffic

README.md
Closes https://fivetran.height.app/T-898484
Tweak readme.md as per Fivetran docs.
Related PR: https://github.com/fivetran/engineering/pull/218227
=> fix(examples): tweak readme as per Fivetran docs

README.md
Links https://fivetran.height.app/T-898484
We need the absolute URL in the readme for proper rendering on Fivetran docs.
=> fix(readme): update link to absolute from relative

examples/common_patterns_for_connectors/cursors/marketstack/connector.py
T-926193
* fixed state date issue
* added logs to make it easy to understand and troubleshoot
* added explicit check and easy to understand error message if the API-key configuration is forgotten.
=> fix(examples): fix the marketstack example

README.md
Closes https://fivetran.height.app/T-932527
=> fix(readme): fix the headings

README_template.md
Related Height task:https://fivetran.height.app/T-898479
=> Add a a template for individual README.mds

.github/PULL_REQUEST_TEMPLATE.md
Closes https://fivetran.height.app/T-947695
Added PR template for PRs.
=> feature(github): add PR template

examples/source_examples/toast/README.md
Links T-925243
embeds the ERD in the README
=> doc(Connector SDK): embed schema in Toast README.md

README.md, examples/common_patterns_for_connectors/azure_keyvault_for_secret_management/README.md, examples/common_patterns_for_connectors/azure_keyvault_for_secret_management/configuration.json, examples/common_patterns_for_connectors/azure_keyvault_for_secret_management/connector.py, examples/common_patterns_for_connectors/azure_keyvault_for_secret_management/requirements.txt
closes https://fivetran.height.app/T-938443
- It fetches the secrets stored in azure keyvault using the azure credentials
- It uses the fetched secrets to connect to postgresql database
- executes a query on postgresql to verify the connection is correct
- Upsert the record to the destination
=> added azure keyvault example

README.md
Link https://fivetran.height.app/T-955484
Updated Readme for supported OS and Arch.
Ref: https://github.com/fivetran/engineering/pull/224176
=> fix(readme): mention properly about supported os and arch

examples/source_examples/toast/README.md
For easy navigation from embedded readme in from the product docs.
linked to https://fivetran.height.app/T-951209/description
`<MENTION A DESCRIPTION OF YOUR CHANGES HERE>`
`<MENTION ABOUT YOUR TESTING DETAILS HERE, ATTACH SCREENSHOTS IF NEEDED (WITHOUT PII)>`
=> Add CTA to example code to README.md

README.md, examples/source_examples/fleetio/README.md, examples/source_examples/fleetio/configuration.json, examples/source_examples/fleetio/connector.py, examples/source_examples/fleetio/requirements.txt
Closes https://fivetran.height.app/T-960994
Adding the Example for syncing data from Fleetio.
Example is taken from the [repository of Fleetio ](https://github.com/fleetio/fivetran-connector/blob/main/connector.py)
There were some changes done to the code written by them:
- Added docstrings and comments for `update()`, `schema()` and other methods
- Added `checkpoint()`
- Added `README` filled by Fleetio
- `fivetran debug`
- Dashboard and destination
=> Task(connector-sdk): Adding example for Fleetio

.github/PULL_REQUEST_TEMPLATE.md
Closes https://fivetran.atlassian.net/browse/RD-949783
Updated PR template with Jira and Python Coding Standards
=> fix(github): updated PR template with Jira and link to Python Coding Standards

template_example_connector/README_template.md
Link https://fivetran.atlassian.net/browse/RD-1008188
Fix readme template to ensure consistent space and bullets pattern.
=> fix(examples): fix readme template 

examples/source_examples/aws_athena/using_boto3/README.md, examples/source_examples/aws_athena/using_sqlalchemy/README.md, examples/source_examples/aws_dynamo_db_authentication/README.md, examples/source_examples/hubspot/README.md, examples/source_examples/newsapi/README.md, examples/source_examples/oauth2_and_accelo_api_connector_multithreading_enabled/README.md, examples/source_examples/s3_csv_validation/README.md, examples/source_examples/smartsheets/README.md, examples/source_examples/sql_server/README.md, examples/source_examples/veeva_vault_using_basic_auth/README.md
Link https://fivetran.atlassian.net/browse/RD-1008188
Added missing readme.md files for Source examples.
=> fix(examples): add missing readme for source examples

.github/workflows/enforce-readme-update.yml, git_hooks/pre-commit
Closes https://fivetran.atlassian.net/browse/RD-1000217
Added git pre-commit hook for auto-formatting Python code files.
=> feature(git): added pre-commit hook for auto-formatting Python files

CODEOWNERS
Link https://fivetran.atlassian.net/browse/RD-968977
Update Codeowners with certain file types instead of too broad coverage.
=> fix(codeowners): update with specific file types for Team Menon

README.md
Closes https://fivetran.atlassian.net/browse/RD-1037077
Mention about contributing to the repo.
=> fix(readme): mention about open-source contributions to repo
